# Uncomment the next line to define a global platform for your project
# platform :ios, '16.2'

target 'MobileApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MobileApp

  target 'MobileAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MobileAppUITests' do
    # Pods for testing
  end

pod 'FirebaseAuth'

end
